// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar configuration for the standalone Career Preparation section.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  careerSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
